- name: set up nessus
  hosts: lab_06
  remote_user: "{{ remote_user_name }}"
  become: yes
  vars:
    remote_user_name: cyber06
    nessus_download_url: "https://www.tenable.com/downloads/api/v1/public/pages/nessus/downloads/13050/download?i_agree_to_tenable_license_agreement=true"

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: downloading the package and installing
      apt:
        deb: "{{ nessus_download_url }}"

    - name: start the nessus daemon
      service:
        name: "nessusd"
        enabled: yes
        state: started
